[package]
name = "koi-syntax"
version = "0.1.0"
authors = ["tahscenery <tahscenery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expect-test = "1.0.1"
rowan = "0.10.0"
unicode-xid = "0.2.1"
