name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  formatting:
    name: Formatting
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run formatter
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
