name: macOS CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  formatting:
    name: Formatting
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run formatter
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
